version: "3"
services:

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  nginx:
     container_name: nginx
     volumes:
       - ./nginx/www:/var/www/html
       - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
       - ./nginx/php-fpm.d/www.conf:/etc/php81/php-fpm.d/www.conf:ro
     image: "trafex/php-nginx:3.1.0"
     networks:
       private_network:
         ipv4_address: 10.2.0.150
     restart: always

  proxy:
    image: "ubuntu/squid:5.7-23.04_edge"
    container_name: squid
    #ports:
      #- "8080:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
    restart: always
    networks:
      private_network:
        ipv4_address: 10.2.0.50

  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wireguard:
    depends_on: [unbound, adguardhome]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100 # Set it to point to adguard
      #- PEERDNS=10.2.0.200 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0
      - ALLOWEDIPS=10.2.0.0/24
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.100 # Points to adguard
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    #command: sh -c "ip link set wg0 mtu 1280"
    networks:
      private_network:
        ipv4_address: 10.2.0.3


  adguardhome:
    depends_on: [unbound]
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    networks:
      private_network:
        ipv4_address: 10.2.0.100
